   # Plot a CDF
    dot_data = {
            "Cloudflare DoT Africa": {"data": pageloads_per_config['cloudflare_dot_Africa'],
                               "color": "#A60628", "linestyle": "-"},
            "Cloudflare DoT America": {"data": pageloads_per_config['cloudflare_dot_North America'],
                               "color": "#A60628", "linestyle": "-."},
            "Cloudflare DoT Europe": {"data": pageloads_per_config['cloudflare_dot_Europe'],
                               "color": "#A60628", "linestyle": ":"},
            "Google DoT Africa": {"data": pageloads_per_config['google_dot_Africa'],
                               "color": "blue", "linestyle": "-"},
            "Google DoT America": {"data": pageloads_per_config['google_dot_North America'],
                               "color": "blue", "linestyle": "-."},
            "Google DoT Europe": {"data": pageloads_per_config['google_dot_Europe'],
                               "color": "blue", "linestyle": ":"},
            "Quad9 DoT Africa": {"data": pageloads_per_config['quad9_dot_Africa'],
                               "color": "green", "linestyle": "-"},
            "Quad9 DoT America": {"data": pageloads_per_config['quad9_dot_North America'],
                               "color": "green", "linestyle": "-."},
            "Quad9 DoT Europe": {"data": pageloads_per_config['quad9_dot_Europe'],
                               "color": "green", "linestyle": ":"},
            "CleanBrowsing DoT Africa": {"data": pageloads_per_config['cleanbrowsing_security_filter_dot_Africa'],
                               "color": "yellow", "linestyle": "-"},
            "CleanBrowsing DoT America": {"data": pageloads_per_config['cleanbrowsing_security_filter_dot_North America'],
                               "color": "yellow", "linestyle": "-."},
            "CleanBrowsing DoT Europe": {"data": pageloads_per_config['cleanbrowsing_security_filter_dot_Europe'],
                               "color": "yellow", "linestyle": ":"},
            "AdGuard DoT Africa": {"data": pageloads_per_config['adguard_default_dot_Africa'],
                               "color": "red", "linestyle": "-"},
            "AdGuard DoT America": {"data": pageloads_per_config['adguard_default_dot_North America'],
                               "color": "red", "linestyle": "-."},
            "AdGuard DoT Europe": {"data": pageloads_per_config['adguard_default_dot_Europe'],
                               "color": "red", "linestyle": ":"}}
    plot_cdf(dot_data, xlimit, 0.1, "Page Load Time (seconds)", filename + "_dot_cdf.pdf")



    doh_data = {"Default DNS": {"data": pageloads_per_config['default_dns_Africa'],
                               "color": "#000000", "linestyle": "-"},
            "Cloudflare DoH Africa": {"data": pageloads_per_config['cloudflare_doh_Africa'],
                               "color": "#A60628", "linestyle": "-"},
            "Cloudflare DoH America": {"data": pageloads_per_config['cloudflare_doh_North America'],
                               "color": "#A60628", "linestyle": "-."},
            "Cloudflare DoH Europe": {"data": pageloads_per_config['cloudflare_doh_Europe'],
                               "color": "#A60628", "linestyle": ":"},
            "Google DoH Africa": {"data": pageloads_per_config['google_doh_Africa'],
                               "color": "blue", "linestyle": "-"},
            "Google DoH America": {"data": pageloads_per_config['google_doh_North America'],
                               "color": "blue", "linestyle": "-."},
            "Google DoH Europe": {"data": pageloads_per_config['google_doh_Europe'],
                               "color": "blue", "linestyle": ":"},
            "Quad9 DoH Africa": {"data": pageloads_per_config['quad9_doh_Africa'],
                               "color": "green", "linestyle": "-"},
            "Quad9 DoH America": {"data": pageloads_per_config['quad9_doh_North America'],
                               "color": "green", "linestyle": "-."},
            "Quad9 DoH Europe": {"data": pageloads_per_config['quad9_doh_Europe'],
                               "color": "green", "linestyle": ":"},
            "CleanBrowsing DoH Africa": {"data": pageloads_per_config['cleanbrowsing_security_filter_doh_Africa'],
                               "color": "yellow", "linestyle": "-"},
            "CleanBrowsing DoH America": {"data": pageloads_per_config['cleanbrowsing_security_filter_doh_North America'],
                               "color": "yellow", "linestyle": "-."},
            "CleanBrowsing DoH Europe": {"data": pageloads_per_config['cleanbrowsing_security_filter_doh_Europe'],
                               "color": "yellow", "linestyle": ":"},
            "AdGuard DoH Africa": {"data": pageloads_per_config['adguard_default_doh_Africa'],
                               "color": "red", "linestyle": "-"},
            "AdGuard DoH America": {"data": pageloads_per_config['adguard_default_doh_North America'],
                               "color": "red", "linestyle": "-."},
            "AdGuard DoH Europe": {"data": pageloads_per_config['adguard_default_doh_Europe'],
                               "color": "red", "linestyle": ":"}}
    plot_cdf(doh_data, xlimit, 0.1, "Page Load Time (seconds)", filename + "_doh_cdf.pdf")



     all_doh_data={
            "quad9_doh_Africa": {"pageloads":[], "color":"#0072B2", "linestyle":"-"},
            "quad9_doh_North America": {"pageloads":[], "color":"#0072B2", "linestyle":":"},
            "quad9_doh_Europe": {"pageloads":[], "color":"#0072B2", "linestyle":"-."},
            "cloudflare_doh_Africa": {"pageloads":[], "color":"red", "linestyle":"-"},
            "cloudflare_doh_North America": {"pageloads":[], "color":"red", "linestyle":":"},
            "cloudflare_doh_Europe": {"pageloads":[], "color":"red", "linestyle":"-."},
            "google_doh_Africa": {"pageloads":[], "color":"green", "linestyle":"-"},
            "google_doh_North America": {"pageloads":[], "color":"green", "linestyle":":"},
            "google_doh_Europe": {"pageloads":[], "color":"green", "linestyle":"-."},
            "cleanbrowsing_security_filter_doh_Africa": {"pageloads":[], "color":"purple", "linestyle":"-"},
            "cleanbrowsing_security_filter_doh_North America": {"pageloads":[], "color":"purple", "linestyle":":"},
            "cleanbrowsing_security_filter_doh_Europe": {"pageloads":[], "color":"purple", "linestyle":"-."},
            "adguard_default_doh_Africa": {"pageloads":[], "color":"orange", "linestyle":"-"},
            "adguard_default_doh_North America": {"pageloads":[], "color":"orange", "linestyle":":"},
            "adguard_default_doh_Europe": {"pageloads":[], "color":"orange", "linestyle":"-."}
    }

    all_dns_data={
            "quad9_dns_Africa": {"pageloads":[], "color":"#0072B2", "linestyle":"-"},
            "quad9_dns_North America": {"pageloads":[], "color":"#0072B2", "linestyle":":"},
            "quad9_dns_Europe": {"pageloads":[], "color":"#0072B2", "linestyle":"-."},
            "cloudflare_dns_Africa": {"pageloads":[], "color":"red", "linestyle":"-"},
            "cloudflare_dns_North America": {"pageloads":[], "color":"red", "linestyle":":"},
            "cloudflare_dns_Europe": {"pageloads":[], "color":"red", "linestyle":"-."},
            "google_dns_Africa": {"pageloads":[], "color":"green", "linestyle":"-"},
            "google_dns_North America": {"pageloads":[], "color":"green", "linestyle":":"},
            "google_dns_Europe": {"pageloads":[], "color":"green", "linestyle":"-."},
            "cleanbrowsing_security_filter_dns_Africa": {"pageloads":[], "color":"purple", "linestyle":"-"},
            "cleanbrowsing_security_filter_dns_North America": {"pageloads":[], "color":"purple", "linestyle":":"},
            "cleanbrowsing_security_filter_dns_Europe": {"pageloads":[], "color":"purple", "linestyle":"-."},
            "adguard_default_dns_Africa": {"pageloads":[], "color":"orange", "linestyle":"-"},
            "adguard_default_dns_North America": {"pageloads":[], "color":"orange", "linestyle":":"},
            "adguard_default_dns_Europe": {"pageloads":[], "color":"orange", "linestyle":"-."}
    }
