options.set_preference('security.ssl.enable_alpn',	true)	
options.set_preference('security.ssl.enable_false_start' ,true)	
options.set_preference('security.ssl.enable_ocsp_must_staple',	true)	
options.set_preference('security.ssl.enable_ocsp_stapling',	true)	
options.set_preference('security.ssl.errorReporting.automatic',	false)	
options.set_preference('security.ssl.errorReporting.enabled',	false)	
options.set_preference('security.ssl.require_safe_negotiation',	false)	
options.set_preference('security.ssl.treat_unsafe_negotiation_as_broken',	false)	
options.set_preference('security.ssl3.dhe_rsa_aes_128_sha',	true)	
options.set_preference('security.ssl3.dhe_rsa_aes_256_sha',	false)	
options.set_preference('security.ssl3.ecdhe_ecdsa_aes_128_gcm_sha256',	false)	
options.set_preference('security.ssl3.ecdhe_ecdsa_aes_128_sha',	false)	
options.set_preference('security.ssl3.ecdhe_ecdsa_aes_256_gcm_sha384',	false)	
options.set_preference('security.ssl3.ecdhe_ecdsa_aes_256_sha',	false)	
options.set_preference('security.ssl3.ecdhe_ecdsa_chacha20_poly1305_sha256',false)	
options.set_preference('security.ssl3.ecdhe_rsa_aes_128_gcm_sha256',false)	
options.set_preference('security.ssl3.ecdhe_rsa_aes_128_sha', false)	
options.set_preference('security.ssl3.ecdhe_rsa_aes_256_gcm_sha384',	false)	
options.set_preference('security.ssl3.ecdhe_rsa_aes_256_sha',	false)	
options.set_preference('security.ssl3.ecdhe_rsa_chacha20_poly1305_sha256',	false)	
options.set_preference('options.set_preference(security.ssl3.rsa_aes_128_sha',	false)	
options.set_preference('security.ssl3.rsa_aes_256_sha',	false)	
options.set_preference('security.ssl3.rsa_des_ede3_sha',	false)	
options.set_preference('security.tls.enable_0rtt_data',	true)	
options.set_preference('security.tls.enable_delegated_credentials',	false)	
options.set_preference('security.tls.enable_post_handshake_auth',	false)	
options.set_preference('security.tls.hello_downgrade_check',	true)	
options.set_preference('security.tls.insecure_fallback_hosts')	
options.set_preference('security.tls.version.enable-deprecated', false)	
options.set_preference('security.tls.version.fallback-limit',	2)	
options.set_preference('security.tls.version.max',	2)	
options.set_preference('security.tls.version.min',	1)