adguard_nofilter_wired_dns=drt_filter.query('vantage_point=="wired" and recursive=="adguard_nofilter" and dns_type=="dns"')['response_time'].dropna()
adguard_nofilter_eduroam_dns=drt_filter.query('vantage_point=="eduroam" and recursive=="adguard_nofilter" and dns_type=="dns"')['response_time'].dropna()
adguard_nofilter_vodacom_4g_dns=drt_filter.query('vantage_point=="vodacom_4g" and recursive=="adguard_nofilter" and dns_type=="dns"')['response_time'].dropna()
adguard_nofilter_wired_dot=drt_filter.query('vantage_point=="wired" and recursive=="adguard_nofilter" and dns_type=="dot"')['response_time'].dropna()
adguard_nofilter_eduroam_dot=drt_filter.query('vantage_point=="eduroam" and recursive=="adguard_nofilter" and dns_type=="dot"')['response_time'].dropna()
adguard_nofilter_vodacom_4g_dot=drt_filter.query('vantage_point=="vodacom_4g" and recursive=="adguard_nofilter" and dns_type=="dot"')['response_time'].dropna()
adguard_nofilter_wired_doh=drt_filter.query('vantage_point=="wired" and recursive=="adguard_nofilter" and dns_type=="doh"')['response_time'].dropna()
adguard_nofilter_eduroam_doh=drt_filter.query('vantage_point=="eduroam" and recursive=="adguard_nofilter" and dns_type=="doh"')['response_time'].dropna()
adguard_nofilter_vodacom_4g_doh=drt_filter.query('vantage_point=="vodacom_4g" and recursive=="adguard_nofilter" and dns_type=="doh"')['response_time'].dropna()

adguard_adblock_wired_dns=drt_filter.query('vantage_point=="wired" and recursive=="adguard_adblock" and dns_type=="dns"')['response_time'].dropna()
adguard_adblock_eduroam_dns=drt_filter.query('vantage_point=="eduroam" and recursive=="adguard_adblock" and dns_type=="dns"')['response_time'].dropna()
adguard_adblock_vodacom_4g_dns=drt_filter.query('vantage_point=="vodacom_4g" and recursive=="adguard_adblock" and dns_type=="dns"')['response_time'].dropna()
adguard_adblock_wired_dot=drt_filter.query('vantage_point=="wired" and recursive=="adguard_adblock" and dns_type=="dot"')['response_time'].dropna()
adguard_adblock_eduroam_dot=drt_filter.query('vantage_point=="eduroam" and recursive=="adguard_adblock" and dns_type=="dot"')['response_time'].dropna()
adguard_adblock_vodacom_4g_dot=drt_filter.query('vantage_point=="vodacom_4g" and recursive=="adguard_adblock" and dns_type=="dot"')['response_time'].dropna()
adguard_adblock_wired_doh=drt_filter.query('vantage_point=="wired" and recursive=="adguard_adblock" and dns_type=="doh"')['response_time'].dropna()
adguard_adblock_eduroam_doh=drt_filter.query('vantage_point=="eduroam" and recursive=="adguard_adblock" and dns_type=="doh"')['response_time'].dropna()
adguard_adblock_vodacom_4g_doh=drt_filter.query('vantage_point=="vodacom_4g" and recursive=="adguard_adblock" and dns_type=="doh"')['response_time'].dropna()

adguard_family_wired_dns=drt_filter.query('vantage_point=="wired" and recursive=="adguard_family" and dns_type=="dns"')['response_time'].dropna()
adguard_family_eduroam_dns=drt_filter.query('vantage_point=="eduroam" and recursive=="adguard_family" and dns_type=="dns"')['response_time'].dropna()
adguard_family_vodacom_4g_dns=drt_filter.query('vantage_point=="vodacom_4g" and recursive=="adguard_family" and dns_type=="dns"')['response_time'].dropna()
adguard_family_wired_dot=drt_filter.query('vantage_point=="wired" and recursive=="adguard_family" and dns_type=="dot"')['response_time'].dropna()
adguard_family_eduroam_dot=drt_filter.query('vantage_point=="eduroam" and recursive=="adguard_family" and dns_type=="dot"')['response_time'].dropna()
adguard_family_vodacom_4g_dot=drt_filter.query('vantage_point=="vodacom_4g" and recursive=="adguard_family" and dns_type=="dot"')['response_time'].dropna()
adguard_family_wired_doh=drt_filter.query('vantage_point=="wired" and recursive=="adguard_family" and dns_type=="doh"')['response_time'].dropna()
adguard_family_eduroam_doh=drt_filter.query('vantage_point=="eduroam" and recursive=="adguard_family" and dns_type=="doh"')['response_time'].dropna()
adguard_family_vodacom_4g_doh=drt_filter.query('vantage_point=="vodacom_4g" and recursive=="adguard_family" and dns_type=="doh"')['response_time'].dropna()



cleanbrowsing_adult_filter_wired_dns=drt_filter.query('vantage_point=="wired" and recursive=="cleanbrowsing_adult_filter" and dns_type=="dns"')['response_time'].dropna()
cleanbrowsing_adult_filter_eduroam_dns=drt_filter.query('vantage_point=="eduroam" and recursive=="cleanbrowsing_adult_filter" and dns_type=="dns"')['response_time'].dropna()
cleanbrowsing_adult_filter_vodacom_4g_dns=drt_filter.query('vantage_point=="vodacom_4g" and recursive=="cleanbrowsing_adult_filter" and dns_type=="dns"')['response_time'].dropna()
cleanbrowsing_adult_filter_wired_doh=drt_filter.query('vantage_point=="wired" and recursive=="cleanbrowsing_adult_filter" and dns_type=="doh"')['response_time'].dropna()
cleanbrowsing_adult_filter_eduroam_doh=drt_filter.query('vantage_point=="eduroam" and recursive=="cleanbrowsing_adult_filter" and dns_type=="doh"')['response_time'].dropna()
cleanbrowsing_adult_filter_vodacom_4g_doh=drt_filter.query('vantage_point=="vodacom_4g" and recursive=="cleanbrowsing_adult_filter" and dns_type=="doh"')['response_time'].dropna()
cleanbrowsing_adult_filter_wired_dot=drt_filter.query('vantage_point=="wired" and recursive=="cleanbrowsing_adult_filter" and dns_type=="dot"')['response_time'].dropna()
cleanbrowsing_adult_filter_eduroam_dot=drt_filter.query('vantage_point=="eduroam" and recursive=="cleanbrowsing_adult_filter" and dns_type=="dot"')['response_time'].dropna()
cleanbrowsing_adult_filter_vodacom_4g_dot=drt_filter.query('vantage_point=="vodacom_4g" and recursive=="cleanbrowsing_adult_filter" and dns_type=="dot"')['response_time'].dropna()

cleanbrowsing_family_filter_wired_dns=drt_filter.query('vantage_point=="wired" and recursive=="cleanbrowsing_family_filter" and dns_type=="dns"')['response_time'].dropna()
cleanbrowsing_family_filter_eduroam_dns=drt_filter.query('vantage_point=="eduroam" and recursive=="cleanbrowsing_family_filter" and dns_type=="dns"')['response_time'].dropna()
cleanbrowsing_family_filter_vodacom_4g_dns=drt_filter.query('vantage_point=="vodacom_4g" and recursive=="cleanbrowsing_family_filter" and dns_type=="dns"')['response_time'].dropna()
cleanbrowsing_family_filter_wired_doh=drt_filter.query('vantage_point=="wired" and recursive=="cleanbrowsing_family_filter" and dns_type=="doh"')['response_time'].dropna()
cleanbrowsing_family_filter_eduroam_doh=drt_filter.query('vantage_point=="eduroam" and recursive=="cleanbrowsing_family_filter" and dns_type=="doh"')['response_time'].dropna()
cleanbrowsing_family_filter_vodacom_4g_doh=drt_filter.query('vantage_point=="vodacom_4g" and recursive=="cleanbrowsing_family_filter" and dns_type=="doh"')['response_time'].dropna()
cleanbrowsing_family_filter_wired_dot=drt_filter.query('vantage_point=="wired" and recursive=="cleanbrowsing_family_filter" and dns_type=="dot"')['response_time'].dropna()
cleanbrowsing_family_filter_eduroam_dot=drt_filter.query('vantage_point=="eduroam" and recursive=="cleanbrowsing_family_filter" and dns_type=="dot"')['response_time'].dropna()
cleanbrowsing_family_filter_vodacom_4g_dot=drt_filter.query('vantage_point=="vodacom_4g" and recursive=="cleanbrowsing_family_filter" and dns_type=="dot"')['response_time'].dropna()

cleanbrowsing_security_filter_wired_dns=drt_filter.query('vantage_point=="wired" and recursive=="cleanbrowsing_security_filter" and dns_type=="dns"')['response_time'].dropna()
cleanbrowsing_security_filter_eduroam_dns=drt_filter.query('vantage_point=="eduroam" and recursive=="cleanbrowsing_security_filter" and dns_type=="dns"')['response_time'].dropna()
cleanbrowsing_security_filter_vodacom_4g_dns=drt_filter.query('vantage_point=="vodacom_4g" and recursive=="cleanbrowsing_security_filter" and dns_type=="dns"')['response_time'].dropna()
cleanbrowsing_security_filter_wired_doh=drt_filter.query('vantage_point=="wired" and recursive=="cleanbrowsing_security_filter" and dns_type=="doh"')['response_time'].dropna()
cleanbrowsing_security_filter_eduroam_doh=drt_filter.query('vantage_point=="eduroam" and recursive=="cleanbrowsing_security_filter" and dns_type=="doh"')['response_time'].dropna()
cleanbrowsing_security_filter_vodacom_4g_doh=drt_filter.query('vantage_point=="vodacom_4g" and recursive=="cleanbrowsing_security_filter" and dns_type=="doh"')['response_time'].dropna()
cleanbrowsing_security_filter_wired_dot=drt_filter.query('vantage_point=="wired" and recursive=="cleanbrowsing_security_filter" and dns_type=="dot"')['response_time'].dropna()
cleanbrowsing_security_filter_eduroam_dot=drt_filter.query('vantage_point=="eduroam" and recursive=="cleanbrowsing_security_filter" and dns_type=="dot"')['response_time'].dropna()
cleanbrowsing_security_filter_vodacom_4g_dot=drt_filter.query('vantage_point=="vodacom_4g" and recursive=="cleanbrowsing_security_filter" and dns_type=="dot"')['response_time'].dropna()



cloudflare_nofilter_wired_dns=drt_filter.query('vantage_point=="wired" and recursive=="cloudflare_nofilter" and dns_type=="dns"')['response_time'].dropna()
cloudflare_nofilter_eduroam_dns=drt_filter.query('vantage_point=="eduroam" and recursive=="cloudflare_nofilter" and dns_type=="dns"')['response_time'].dropna()
cloudflare_nofilter_vodacom_4g_dns=drt_filter.query('vantage_point=="vodacom_4g" and recursive=="cloudflare_nofilter" and dns_type=="dns"')['response_time'].dropna()
cloudflare_nofilter_wired_doh=drt_filter.query('vantage_point=="wired" and recursive=="cloudflare_nofilter" and dns_type=="doh"')['response_time'].dropna()
cloudflare_nofilter_eduroam_doh=drt_filter.query('vantage_point=="eduroam" and recursive=="cloudflare_nofilter" and dns_type=="doh"')['response_time'].dropna()
cloudflare_nofilter_vodacom_4g_doh=drt_filter.query('vantage_point=="vodacom_4g" and recursive=="cloudflare_nofilter" and dns_type=="doh"')['response_time'].dropna()
cloudflare_nofilter_wired_dot=drt_filter.query('vantage_point=="wired" and recursive=="cloudflare_nofilter" and dns_type=="dot"')['response_time'].dropna()
cloudflare_nofilter_eduroam_dot=drt_filter.query('vantage_point=="eduroam" and recursive=="cloudflare_nofilter" and dns_type=="dot"')['response_time'].dropna()
cloudflare_nofilter_vodacom_4g_dot=drt_filter.query('vantage_point=="vodacom_4g" and recursive=="cloudflare_nofilter" and dns_type=="dot"')['response_time'].dropna()

cloudflare_family_wired_dns=drt_filter.query('vantage_point=="wired" and recursive=="cloudflare_family" and dns_type=="dns"')['response_time'].dropna()
cloudflare_family_eduroam_dns=drt_filter.query('vantage_point=="eduroam" and recursive=="cloudflare_family" and dns_type=="dns"')['response_time'].dropna()
cloudflare_family_vodacom_4g_dns=drt_filter.query('vantage_point=="vodacom_4g" and recursive=="cloudflare_family" and dns_type=="dns"')['response_time'].dropna()
cloudflare_family_wired_doh=drt_filter.query('vantage_point=="wired" and recursive=="cloudflare_family" and dns_type=="doh"')['response_time'].dropna()
cloudflare_family_eduroam_doh=drt_filter.query('vantage_point=="eduroam" and recursive=="cloudflare_family" and dns_type=="doh"')['response_time'].dropna()
cloudflare_family_vodacom_4g_doh=drt_filter.query('vantage_point=="vodacom_4g" and recursive=="cloudflare_family" and dns_type=="doh"')['response_time'].dropna()
cloudflare_family_wired_dot=drt_filter.query('vantage_point=="wired" and recursive=="cloudflare_family" and dns_type=="dot"')['response_time'].dropna()
cloudflare_family_eduroam_dot=drt_filter.query('vantage_point=="eduroam" and recursive=="cloudflare_family" and dns_type=="dot"')['response_time'].dropna()
cloudflare_family_vodacom_4g_dot=drt_filter.query('vantage_point=="vodacom_4g" and recursive=="cloudflare_family" and dns_type=="dot"')['response_time'].dropna()

cloudflare_security_wired_dns=drt_filter.query('vantage_point=="wired" and recursive=="cloudflare_security" and dns_type=="dns"')['response_time'].dropna()
cloudflare_security_eduroam_dns=drt_filter.query('vantage_point=="eduroam" and recursive=="cloudflare_security" and dns_type=="dns"')['response_time'].dropna()
cloudflare_security_vodacom_4g_dns=drt_filter.query('vantage_point=="vodacom_4g" and recursive=="cloudflare_security" and dns_type=="dns"')['response_time'].dropna()
cloudflare_security_wired_doh=drt_filter.query('vantage_point=="wired" and recursive=="cloudflare_security" and dns_type=="doh"')['response_time'].dropna()
cloudflare_security_eduroam_doh=drt_filter.query('vantage_point=="eduroam" and recursive=="cloudflare_security" and dns_type=="doh"')['response_time'].dropna()
cloudflare_security_vodacom_4g_doh=drt_filter.query('vantage_point=="vodacom_4g" and recursive=="cloudflare_security" and dns_type=="doh"')['response_time'].dropna()
cloudflare_security_wired_dot=drt_filter.query('vantage_point=="wired" and recursive=="cloudflare_security" and dns_type=="dot"')['response_time'].dropna()
cloudflare_security_eduroam_dot=drt_filter.query('vantage_point=="eduroam" and recursive=="cloudflare_security" and dns_type=="dot"')['response_time'].dropna()
cloudflare_security_vodacom_4g_dot=drt_filter.query('vantage_point=="vodacom_4g" and recursive=="cloudflare_security" and dns_type=="dot"')['response_time'].dropna()

quad9_nofilter_wired_dns=drt_filter.query('vantage_point=="wired" and recursive=="quad9_nofilter" and dns_type=="dns"')['response_time'].dropna()
quad9_nofilter_eduroam_dns=drt_filter.query('vantage_point=="eduroam" and recursive=="quad9_nofilter" and dns_type=="dns"')['response_time'].dropna()
quad9_nofilter_vodacom_4g_dns=drt_filter.query('vantage_point=="vodacom_4g" and recursive=="quad9_nofilter" and dns_type=="dns"')['response_time'].dropna()
quad9_nofilter_wired_doh=drt_filter.query('vantage_point=="wired" and recursive=="quad9_nofilter" and dns_type=="doh"')['response_time'].dropna()
quad9_nofilter_eduroam_doh=drt_filter.query('vantage_point=="eduroam" and recursive=="quad9_nofilter" and dns_type=="doh"')['response_time'].dropna()
quad9_nofilter_vodacom_4g_doh=drt_filter.query('vantage_point=="vodacom_4g" and recursive=="quad9_nofilter" and dns_type=="doh"')['response_time'].dropna()
quad9_nofilter_wired_dot=drt_filter.query('vantage_point=="wired" and recursive=="quad9_nofilter" and dns_type=="dot"')['response_time'].dropna()
quad9_nofilter_eduroam_dot=drt_filter.query('vantage_point=="eduroam" and recursive=="quad9_nofilter" and dns_type=="dot"')['response_time'].dropna()
quad9_nofilter_vodacom_4g_dot=drt_filter.query('vantage_point=="vodacom_4g" and recursive=="quad9_nofilter" and dns_type=="dot"')['response_time'].dropna()

quad9_security_wired_dns=drt_filter.query('vantage_point=="wired" and recursive=="quad9_security" and dns_type=="dns"')['response_time'].dropna()
quad9_security_eduroam_dns=drt_filter.query('vantage_point=="eduroam" and recursive=="quad9_security" and dns_type=="dns"')['response_time'].dropna()
quad9_security_vodacom_4g_dns=drt_filter.query('vantage_point=="vodacom_4g" and recursive=="quad9_security" and dns_type=="dns"')['response_time'].dropna()
quad9_security_wired_doh=drt_filter.query('vantage_point=="wired" and recursive=="quad9_security" and dns_type=="doh"')['response_time'].dropna()
quad9_security_eduroam_doh=drt_filter.query('vantage_point=="eduroam" and recursive=="quad9_security" and dns_type=="doh"')['response_time'].dropna()
quad9_security_vodacom_4g_doh=drt_filter.query('vantage_point=="vodacom_4g" and recursive=="quad9_security" and dns_type=="doh"')['response_time'].dropna()
quad9_security_wired_dot=drt_filter.query('vantage_point=="wired" and recursive=="quad9_security" and dns_type=="dot"')['response_time'].dropna()
quad9_security_eduroam_dot=drt_filter.query('vantage_point=="eduroam" and recursive=="quad9_security" and dns_type=="dot"')['response_time'].dropna()
quad9_security_vodacom_4g_dot=drt_filter.query('vantage_point=="vodacom_4g" and recursive=="quad9_security" and dns_type=="dot"')['response_time'].dropna()


(CFN\_Do53, CFF\_Do53),(CFN\_Do53, CFS\_Do53), (CFN\_DoH, CFF\_DoH), (CFN\_DoH, CFS\_DoH), (CFN\_DoT, CFF\_DoT), (CFN\_DoT, CFS\_DoT), (CFF\_Do53, CFS\_Do53),(CFF\_DoH, CFS\_DoH), (CFF\_DoT, CFS\_DoT)  